// Demo Data — Full enterprise cybersecurity dataset for acmecorp.io

export const DEMO_SCAN = {
  id: 'demo-scan-001',
  target: 'acmecorp.io',
  domain: 'acmecorp.io',
  ars_score: 84,
  risk_level: 'CRITICAL' as const,
  estimated_exploit_time: '18-24 hours',
  estimated_time_to_exploit_hours: 21,
  primary_attack_vector: 'Phishing → VPN → Lateral movement',
  primary_entry_path: 'Phishing email → compromised VPN credentials → admin panel access',
  scan_duration_seconds: 47,
  confidence: 94,
  timestamp: new Date(Date.now() - 1000 * 60 * 23).toISOString(),
  findings: [
    {
      id: 'f1',
      severity: 'CRITICAL' as const,
      source: 'Shodan' as const,
      title: 'Exposed Admin Panel at /wp-admin',
      description: 'Publicly accessible WordPress admin panel detected on acmecorp.io. No rate limiting or geo-restriction.',
      meaning: 'An attacker can perform unlimited login attempts (brute force) directly against your admin interface.',
      isReal: false,
      cvss: 9.8,
      cve: null,
      remediation: 'Move admin panel to a non-standard path and restrict access by IP allowlist.',
    },
    {
      id: 'f2',
      severity: 'CRITICAL' as const,
      source: 'Shodan' as const,
      title: 'Misconfigured S3 Bucket — Public Read',
      description: 'S3 bucket "acmecorp-assets-staging" has public READ access enabled. Contains employee data and API configs.',
      meaning: 'Anyone on the internet can download your internal configuration files, employee data, and API secrets.',
      isReal: false,
      cvss: 9.1,
      cve: null,
      remediation: 'Block all public access to S3 buckets via AWS Console → Block Public Access. Audit existing permissions with AWS Access Analyzer.',
    },
    {
      id: 'f3',
      severity: 'HIGH' as const,
      source: 'Shodan' as const,
      title: 'Apache 2.4.49 — CVE-2021-41773 Path Traversal',
      description: 'Apache HTTP Server version 2.4.49 detected. Vulnerable to path traversal and RCE if mod_cgi enabled.',
      meaning: 'Attacker can read sensitive files outside the web root (/etc/passwd, /etc/shadow, AWS credentials).',
      isReal: false,
      cvss: 7.5,
      cve: 'CVE-2021-41773',
      remediation: 'Upgrade Apache to 2.4.51 or later immediately. This vulnerability has active exploits in the wild.',
    },
    {
      id: 'f4',
      severity: 'HIGH' as const,
      source: 'HaveIBeenPwned' as const,
      title: 'No MFA Enforced on Okta SSO',
      description: 'Okta SSO configuration allows password-only authentication for 47% of user accounts.',
      meaning: 'A credential stuffing attack using leaked passwords has a high success rate against your SSO.',
      isReal: false,
      cvss: 7.2,
      cve: null,
      remediation: 'Enforce MFA for all users in Okta Admin → Security → Authenticators. Use FIDO2/WebAuthn for highest security.',
    },
    {
      id: 'f5',
      severity: 'HIGH' as const,
      source: 'GitHub' as const,
      title: 'Leaked API Key in Public GitHub Repository',
      description: 'Active Stripe publishable + secret key found in commit history of public repo "acmecorp/marketing-site".',
      meaning: 'Attacker can make unauthorized charges, access customer data, and issue refunds using your payment processor.',
      isReal: false,
      cvss: 8.1,
      cve: null,
      remediation: 'Revoke the key immediately in Stripe Dashboard. Rotate all secrets. Use git-secrets or truffleHog in your CI/CD pipeline.',
    },
    {
      id: 'f6',
      severity: 'MEDIUM' as const,
      source: 'DNS' as const,
      title: 'Open SMTP Relay Detected on mail.acmecorp.io',
      description: 'Mail server accepts and forwards email for third-party domains without authentication.',
      meaning: 'Attackers can send phishing emails that appear to originate from your domain, bypassing spam filters.',
      isReal: false,
      cvss: 5.3,
      cve: null,
      remediation: 'Configure your mail server to only relay for authenticated users or specific IP ranges. Add SPF, DKIM, and DMARC records.',
    },
    {
      id: 'f7',
      severity: 'MEDIUM' as const,
      source: 'Security Headers' as const,
      title: 'TLS 1.0 Still Supported',
      description: 'acmecorp.io TLS configuration accepts TLS 1.0 connections. POODLE and BEAST attacks applicable.',
      meaning: 'Legacy clients connecting via TLS 1.0 may have their session data intercepted by a man-in-the-middle attacker.',
      isReal: false,
      cvss: 5.9,
      cve: 'CVE-2014-3566',
      remediation: 'Disable TLS 1.0 and 1.1. Configure minimum TLS version to 1.2, preferably 1.3.',
    },
    {
      id: 'f8',
      severity: 'LOW' as const,
      source: 'Security Headers' as const,
      title: 'Missing Critical Security Headers',
      description: 'Content-Security-Policy, HSTS, X-Frame-Options, and X-Content-Type-Options headers absent.',
      meaning: 'Your site is more vulnerable to XSS attacks, clickjacking, and MIME-type confusion attacks.',
      isReal: false,
      cvss: 3.7,
      cve: null,
      remediation: 'Add security headers via your web server config or a CDN like Cloudflare. Use securityheaders.com to verify.',
    },
  ],
  real_sources_used: [],
  scan_duration_s: 47,
};

export const DEMO_HONEYPOTS = [
  {
    id: 'hp-001',
    name: 'Fake Admin Portal',
    type: 'admin-portal',
    url: 'https://acmecorp.io/admin-internal',
    status: 'active',
    interaction_count: 12,
    last_triggered: new Date(Date.now() - 1000 * 60 * 47).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
  },
  {
    id: 'hp-002',
    name: 'Decoy S3 Bucket',
    type: 'cloud-bucket',
    url: 's3://acmecorp-assets-backup-prod',
    status: 'active',
    interaction_count: 7,
    last_triggered: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
  },
  {
    id: 'hp-003',
    name: 'Ghost VPN Endpoint',
    type: 'vpn-endpoint',
    url: 'vpn.acmecorp-secure.io:1194',
    status: 'active',
    interaction_count: 3,
    last_triggered: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];

export const DEMO_ALERTS = [
  {
    id: 'alert-001',
    severity: 'CRITICAL' as const,
    attacker_classification: 'APT29 (Cozy Bear)',
    attacker_ip: '185.220.101.47',
    attacker_geo: { country: 'Russia', flag: '🇷🇺', city: 'Moscow', isp: 'Tor Network', asn: 'AS60117' },
    attacker_tool: 'Hydra, Burp Suite, Mimikatz',
    confidence_score: 0.94,
    event_type: 'Admin Portal Accessed',
    honeypot_name: 'Fake Admin Portal',
    honeypot_id: 'hp-001',
    is_read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 44).toISOString(),
    // Legacy compat fields
    timestamp: new Date(Date.now() - 1000 * 60 * 44).toISOString(),
    ip: '185.220.101.47',
    country_flag: '🇷🇺',
    country: 'Russia',
    network_tag: 'Tor Exit Node',
    user_agent: 'Mozilla/5.0 (Windows NT 10.0; Win64)',
    asset_used: 'Fake Admin Portal',
    asset_value: '/admin-internal',
    behavior: {
      requests: '1,247 requests in 8 minutes',
      pattern: 'Credential stuffing → authenticated session',
      fingerprint: 'Chrome 119, Windows 11, Canvas fingerprint collected',
    },
    classification: { label: 'Human Attacker' as const, confidence: 94 },
    attack_path: [
      { step: 1, label: 'Asset Discovery via Shodan + LinkedIn OSINT', triggered: false, predicted: false },
      { step: 2, label: 'Credential stuffing (1,247 attempts)', triggered: false, predicted: false },
      { step: 3, label: 'Accessed decoy admin portal — TRAP TRIGGERED', triggered: true, predicted: false },
      { step: 4, label: 'Lateral movement attempt (Mimikatz signatures)', triggered: false, predicted: true },
      { step: 5, label: 'Exfiltrate /etc/passwd and AWS credentials', triggered: false, predicted: true },
    ],
    status: 'open' as const,
  },
  {
    id: 'alert-002',
    severity: 'HIGH' as const,
    attacker_classification: 'Unknown',
    attacker_ip: '45.33.32.156',
    attacker_geo: { country: 'United States', flag: '🇺🇸', city: 'Reston', isp: 'Linode LLC', asn: 'AS63949' },
    attacker_tool: 'Nmap, Python-requests',
    confidence_score: 0.72,
    event_type: 'S3 Bucket Enumeration Attempt',
    honeypot_name: 'Decoy S3 Bucket',
    honeypot_id: 'hp-002',
    is_read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    ip: '45.33.32.156',
    country_flag: '🇺🇸',
    country: 'United States',
    network_tag: 'Cloud VPS',
    user_agent: 'python-requests/2.31.0',
    asset_used: 'Decoy S3 Bucket',
    asset_value: 's3://acmecorp-assets-backup-prod',
    behavior: {
      requests: '43 requests in 2 minutes',
      pattern: 'Bucket enumeration → object listing → download attempt',
      fingerprint: 'AWS CLI v2 signature detected',
    },
    classification: { label: 'Automated Recon Bot' as const, confidence: 72 },
    attack_path: [
      { step: 1, label: 'Target bucket discovered via exposed policy', triggered: false, predicted: false },
      { step: 2, label: 'Object listing via aws s3 ls — TRAP TRIGGERED', triggered: true, predicted: false },
      { step: 3, label: 'Mass download attempt of files', triggered: false, predicted: true },
    ],
    status: 'open' as const,
  },
  {
    id: 'alert-003',
    severity: 'HIGH' as const,
    attacker_classification: 'APT41',
    attacker_ip: '103.92.28.94',
    attacker_geo: { country: 'China', flag: '🇨🇳', city: 'Chengdu', isp: 'China Telecom', asn: 'AS4134' },
    attacker_tool: 'Custom scanner, curl',
    confidence_score: 0.81,
    event_type: 'VPN Endpoint Probe',
    honeypot_name: 'Ghost VPN Endpoint',
    honeypot_id: 'hp-003',
    is_read: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 7).toISOString(),
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 7).toISOString(),
    ip: '103.92.28.94',
    country_flag: '🇨🇳',
    country: 'China',
    network_tag: 'China Telecom AS4134',
    user_agent: 'curl/7.81.0',
    asset_used: 'Ghost VPN Endpoint',
    asset_value: 'vpn.acmecorp-secure.io:1194',
    behavior: {
      requests: '18 probes over 45 minutes',
      pattern: 'VPN fingerprinting → tunnel negotiation attempt',
      fingerprint: 'OpenVPN client signature, certificate pinning bypass attempt',
    },
    classification: { label: 'Human Attacker' as const, confidence: 81 },
    attack_path: [
      { step: 1, label: 'VPN endpoint discovered via certificate transparency', triggered: false, predicted: false },
      { step: 2, label: 'Tunnel negotiation attempt — TRAP TRIGGERED', triggered: true, predicted: false },
      { step: 3, label: 'Internal network pivot attempt', triggered: false, predicted: true },
    ],
    status: 'flagged' as const,
  },
  {
    id: 'alert-004',
    severity: 'MEDIUM' as const,
    attacker_classification: 'Script Kiddie',
    attacker_ip: '198.51.100.42',
    attacker_geo: { country: 'Netherlands', flag: '🇳🇱', city: 'Amsterdam', isp: 'Digital Ocean', asn: 'AS14061' },
    attacker_tool: 'sqlmap, Nikto',
    confidence_score: 0.55,
    event_type: 'SQL Injection Scan',
    honeypot_name: 'Fake Admin Portal',
    honeypot_id: 'hp-001',
    is_read: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 21).toISOString(),
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 21).toISOString(),
    ip: '198.51.100.42',
    country_flag: '🇳🇱',
    country: 'Netherlands',
    network_tag: 'DigitalOcean VPS',
    user_agent: 'sqlmap/1.7.8#stable',
    asset_used: 'Fake Admin Portal',
    asset_value: '/admin-internal?id=1',
    behavior: {
      requests: '312 requests over 1 hour',
      pattern: 'Automated SQL injection patterns via sqlmap',
      fingerprint: 'sqlmap user-agent detected, typical payload signatures',
    },
    classification: { label: 'Automated Recon Bot' as const, confidence: 55 },
    attack_path: [
      { step: 1, label: 'Admin form parameter discovered', triggered: false, predicted: false },
      { step: 2, label: 'SQL injection payload sent — TRAP TRIGGERED', triggered: true, predicted: false },
      { step: 3, label: 'Database dump attempt', triggered: false, predicted: true },
    ],
    status: 'dismissed' as const,
  },
];

export const DEMO_REPLAY_SESSION = {
  id: 'replay-001',
  alert_id: 'alert-001',
  confidence_score: 0.94,
  attacker_profile: {
    classification: 'APT29 (Cozy Bear)',
    origin: 'Russia',
    motivation: 'Espionage / Data theft',
    sophistication: 'Nation-state',
    confidence: 76,
    known_targets: ['US Government', 'European Energy', 'Tech Companies'],
    ttps: ['T1566 Phishing', 'T1078 Valid Accounts', 'T1003 OS Credential Dumping'],
  },
  steps: [
    {
      step: 1,
      title: 'Asset Discovery',
      subtitle: 'OSINT reconnaissance via Shodan + LinkedIn',
      timestamp: '2024-01-15T14:23:11Z',
      tool: 'Shodan, Maltego',
      ip: '185.220.101.47',
      confidence: 94,
      severity: 'info' as const,
      details:
        'Attacker mapped 23 exposed services including admin portal at /wp-admin. Found 3 employee LinkedIn profiles with IT credentials visible in job postings. Subdomain enumeration revealed 8 staging subdomains.',
    },
    {
      step: 2,
      title: 'Credential Stuffing',
      subtitle: 'Automated login attempts using leaked credentials',
      timestamp: '2024-01-15T14:31:44Z',
      tool: 'Hydra, Burp Suite',
      ip: '185.220.101.47',
      confidence: 89,
      severity: 'high' as const,
      details:
        '1,247 login attempts over 8 minutes using breach database credentials from Collection #1 leak. Triggered rate limiter at attempt 89. Switched to slower attack to evade detection.',
    },
    {
      step: 3,
      title: 'Trap Triggered',
      subtitle: 'Accessed decoy admin portal — MirrorTrap activated',
      timestamp: '2024-01-15T14:44:02Z',
      tool: 'Chrome 119, Windows 11',
      ip: '185.220.101.47',
      confidence: 100,
      severity: 'critical' as const,
      details:
        'Attacker authenticated using honeypot credential "admin@acmecorp-internal.io". Full session captured. Browser fingerprint: Chrome/119 Windows. Canvas fingerprint collected. TLS certificate pinned. Geolocation: Moscow, Russia via Tor exit node.',
    },
    {
      step: 4,
      title: 'Lateral Movement Attempt',
      subtitle: 'Attempted to pivot to internal systems',
      timestamp: '2024-01-15T14:44:58Z',
      tool: 'Mimikatz signatures detected',
      ip: '185.220.101.47',
      confidence: 78,
      severity: 'critical' as const,
      details:
        'Post-authentication requests attempted to access /api/internal/users and /api/keys. Mimikatz user-agent signature detected in one request. All requests served fake data from honeypot environment.',
    },
    {
      step: 5,
      title: 'Attacker Contained',
      subtitle: 'Session isolated — real systems fully protected',
      timestamp: '2024-01-15T14:45:12Z',
      tool: 'MirrorTrap PhantomShield',
      ip: '185.220.101.47',
      confidence: 100,
      severity: 'success' as const,
      details:
        'All subsequent requests served from honeypot environment. Attacker believes they are inside the real system. IP flagged across 14 threat intelligence feeds. Law enforcement notification generated. Evidence package created.',
    },
  ],
  predicted_next_moves: [
    'Attempt privilege escalation via sudo abuse or SUID binaries',
    'Search for AWS/GCP credentials in environment files and ~/.aws/credentials',
    'Attempt to exfiltrate /etc/passwd and /etc/shadow',
    'Install persistent backdoor via cron job or systemd service',
    'Lateral movement to adjacent systems via SSH keys',
  ],
  created_at: new Date(Date.now() - 1000 * 60 * 44).toISOString(),
};
